# Global
resource: "reanalysis-era5-land"
dataset_short_name: "reanalysis-era5-land"
format: "netcdf"
day: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11",
      "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22",
      "23", "24", "25", "26", "27", "28", "29", "30", "31"]
time: ["00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00",
       "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00",
       "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00",
       "21:00", "22:00", "23:00"]
       
# Request
area: [6, -55, 2, -52]
year: [1950]
month: [1, 2]
variables: [
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
    "2m_dewpoint_temperature",
    "2m_temperature",
    "surface_net_solar_radiation",
    "surface_pressure",
    "total_precipitation"
  ]

# Singularity
cdsapi: "https://github.com/sylvainschmitt/singularity-cdsapi/releases/download/0.0.2/sylvainschmitt-singularity-cdsapi.latest.sif"
