__default__:
  jobname: "default"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
retrieve:
  jobname: "retrieve"
  mem: "10G"
  cpus: 1
  time: "48:00:00"

merge_year:
  jobname: "merge_year"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  
merge_all:
  jobname: "merge_all"
  mem: "10G"
  cpus: 1
  time: "48:00:00"
  